# Generated by Django 4.2.1 on 2023-06-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_clients_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ('email',), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='sending',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
