# Generated by Django 4.2.1 on 2023-06-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_clients_options_alter_sending_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ('email',), 'permissions': [('can_view_client', 'Can view client'), ('can_block_client', 'Can block client')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='sending',
            options={'permissions': [('set_sending_status', 'Can set sending status'), ('can_view_sending', 'Can view sending')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
